### ISSUE TITLE
出现了Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference问题。

### ISSUE THREAD

**Issue by Evilleon** [ljm17/PieView#1]
我在使用您的饼状图源代码时报了异常`  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference`
具体问题为
`at com.example.myapplication2.PieView.drawTextInner(PieView.java:255)
        at com.example.myapplication2.PieView.drawByNormal(PieView.java:159)
        at com.example.myapplication2.PieView.draw(PieView.java:119)`
这一部分的方法是
`private void drawTextInner(Canvas canvas){
        if (disPlayPercent) {
            for (int i = 0; i < count; i++) {
                float sweepAngle = getData().get(i).getData() / sumData * 360f;
                canvas.save();
                //当前模块角平分线的sin和cos值
                float mathCos = (float) (Math.cos((sweepAngle / 2 + mCurrentDegree) / 180f * Math.PI));
                float mathSin = (float) (Math.sin((sweepAngle / 2 + mCurrentDegree) / 180f * Math.PI));
                if (getData().get(i).isRaised()){
                    //若该板块设置凸起，平移画布，使其与周边各块产生间距，并突出
                    canvas.translate(mathCos * mSpace, mathSin * mSpace);
                }

                //获取文字高度，因水平已居中
                //设置文字格式
                DecimalFormat format = new DecimalFormat("#0.00%");
                String text = format.format(sweepAngle / 360f);
                Paint.FontMetrics metrics = mBlockTextPaint.getFontMetrics();
                float textRadius = (1 + mAlphaRadiusPercent) * mRadius / 2;
                //绘制模块文字
                canvas.drawText(getData().get(i).getMsg(), textRadius * mathCos,
                        textRadius * mathSin - Math.abs(metrics.descent), mBlockTextPaint);
                //绘制模块百分比
                canvas.drawText(text, textRadius * mathCos,
                        textRadius * mathSin + Math.abs(metrics.ascent), mBlockTextPaint);
                canvas.restore();
                mCurrentDegree += sweepAngle;
            }
        }else {
            for (int i = 0; i < count; i++) {
                float sweepAngle = getData().get(i).getData() / sumData * 360f;
                canvas.save();
                //当前模块角平分线的sin和cos值
                float mathCos = (float) (Math.cos((sweepAngle / 2 + mCurrentDegree) / 180f * Math.PI));
                float mathSin = (float) (Math.sin((sweepAngle / 2 + mCurrentDegree) / 180f * Math.PI));
                if (getData().get(i).isRaised()){
                    //若该板块设置凸起，平移画布，使其与周边各块产生间距，并突出
                    canvas.translate(mathCos * mSpace, mathSin * mSpace);
                }
                //获取文字高度，因水平已居中
                String text = getData().get(i).getMsg();
                Paint.FontMetrics metrics = mBlockTextPaint.getFontMetrics();
                float textHeight = Math.abs(metrics.descent - metrics.ascent);
                float textRadius = (1 + mAlphaRadiusPercent) * mRadius / 2;
                //绘制模块文字
                canvas.drawText(text, textRadius * mathCos,
                        textRadius * mathSin + textHeight / 2 - metrics.descent, mBlockTextPaint);
                canvas.restore();
                mCurrentDegree += sweepAngle;
            }
        }
    }`
具体位置是绘制模块文字下第一句
第二个错误的方法
`private void drawByNormal(Canvas canvas){
        //循环绘制各模块
        for (int i=0;i<count;i++){
            if (0 == getData().get(i).getColor()){
                int color = getRandColor();
                mOutPaint.setColor(color);
                getData().get(i).setColor(color);
            }else {
                mOutPaint.setColor(getData().get(i).getColor());
            }
            //计算该板块角度
            float sweepAngle = getData().get(i).getData()/sumData*360f;
            //保存当前画布状态
            canvas.save();
            //当前模块角平分线的sin和cos值
            if (getData().get(i).isRaised()){
                float mathCos = (float) (Math.cos((sweepAngle/2+mCurrentDegree)/180f*Math.PI));
                float mathSin = (float) (Math.sin((sweepAngle/2+mCurrentDegree)/180f*Math.PI));
                //若该板块设置凸起，平移画布，使其与周边各块产生间距，并突出
                canvas.translate(mathCos*mSpace, mathSin*mSpace);
            }
            //绘制外圆
            canvas.drawArc(mRadiusRectF,mCurrentDegree,sweepAngle,true,mOutPaint);
            //恢复平移前的状态
            canvas.restore();

            mCurrentDegree += sweepAngle;
        }

        mAlphaPaint.setAlpha((int) (mAlpha*255));
        canvas.drawCircle(0,0,mRadius*mAlphaRadiusPercent,mAlphaPaint);
        canvas.drawCircle(0,0,mRadius*mHoleRadiusPercent,mHolePaint);

        drawTextInner(canvas);

        if (showCenterText) {
            //绘制中心文字
            Paint.FontMetrics metrics = mCenterTextPaint.getFontMetrics();
            float textHeight = Math.abs(metrics.descent - metrics.ascent);
            canvas.drawText(mCenterText, 0, textHeight / 2 - metrics.descent, mCenterTextPaint);
        }
    }`
具体位置是drawTextInner（canvas）;
第三个错误方法是
`public void draw(Canvas canvas) {
        super.draw(canvas);
        //将画布绘成白色
        canvas.drawColor(Color.WHITE);
        //平移画布，使（0,0）点至中心，便于计算
        canvas.translate(getWidth()/2,getHeight()/2);
        calculate();

        if (showAnimator){
            drawByAnim(canvas);
        }else {
            drawByNormal(canvas);
        }
    }`
具体位置是drawByNormal（canvas）;

为什么会出现这样的问题？该如何解决呢？希望您能解答我的疑惑。

**Comment by ljm17** [comment]
这应该是由于你传入的PieEntry的msg为null，绘制文字时，canvas.drawText()文字为空报的空指针
